"""add appointment_time to encounters

Revision ID: 1057da57fb1d
Revises: 735579d2a0e3
Create Date: 2025-11-07 15:31:01.443837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1057da57fb1d'
down_revision = '735579d2a0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_column('appointment_time')

    # ### end Alembic commands ###
