"""Add hotel reservation model

Revision ID: 280cc95ef1af
Revises: dcf1bc0a88ff
Create Date: 2025-11-07 01:53:13.284746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280cc95ef1af'
down_revision = 'dcf1bc0a88ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('hotel_address', sa.Text(), nullable=True),
    sa.Column('hotel_phone', sa.String(length=20), nullable=True),
    sa.Column('hotel_stars', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=True),
    sa.Column('total_hotel_cost', sa.Float(), nullable=True),
    sa.Column('transfer_included', sa.Boolean(), nullable=True),
    sa.Column('transfer_type', sa.String(length=50), nullable=True),
    sa.Column('transfer_cost', sa.Float(), nullable=True),
    sa.Column('airport_code', sa.String(length=10), nullable=True),
    sa.Column('airport_name', sa.String(length=200), nullable=True),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('breakfast_included', sa.Boolean(), nullable=True),
    sa.Column('wifi_included', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirmation_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_reservations')
    # ### end Alembic commands ###
