"""add new module toggles to settings

Revision ID: 41717461b7cc
Revises: f3f85488e7d7
Create Date: 2025-11-07 15:55:59.493785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41717461b7cc'
down_revision = 'f3f85488e7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_aesthetic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_bariatric', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_ivf', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_checkup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('enable_checkup')
        batch_op.drop_column('enable_ivf')
        batch_op.drop_column('enable_bariatric')
        batch_op.drop_column('enable_aesthetic')

    # ### end Alembic commands ###
