"""Add new medical modules to distributor

Revision ID: 48cd6e121798
Revises: 41717461b7cc
Create Date: 2025-11-07 18:29:43.756462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cd6e121798'
down_revision = '41717461b7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_aesthetic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_bariatric', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_ivf', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_checkup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('enable_checkup')
        batch_op.drop_column('enable_ivf')
        batch_op.drop_column('enable_bariatric')
        batch_op.drop_column('enable_aesthetic')

    # ### end Alembic commands ###
