"""add_message_language_fields

Revision ID: 65d93fe8079d
Revises: a1b2c3d4e5f7
Create Date: 2025-11-10 19:18:42.135304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d93fe8079d'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('backup_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('backup_schedule',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'daily'"))
        batch_op.alter_column('api_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('performance_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'standard'"))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_encounter_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.alter_column('pdf_language',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'tr'"))
        batch_op.alter_column('currency_format_locale',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'tr_TR'"))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('target_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('translated_content', sa.Text(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('patient_journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_journeys_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    with op.batch_alter_table('quote_approvals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_index(batch_op.f('ix_quote_approvals_encounter_id'))
        batch_op.drop_index(batch_op.f('ix_quote_approvals_token'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=False)

    with op.batch_alter_table('quote_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_approvals_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_approvals_encounter_id'), ['encounter_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=False)

    with op.batch_alter_table('patient_journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_journeys_created_at'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('translated_content')
        batch_op.drop_column('target_language')
        batch_op.drop_column('detected_language')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.alter_column('currency_format_locale',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'tr_TR'"))
        batch_op.alter_column('pdf_language',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'tr'"))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_distributor_id'), ['distributor_id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('performance_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'standard'"))
        batch_op.alter_column('api_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('backup_schedule',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'daily'"))
        batch_op.alter_column('backup_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
