"""Add currency fields to dental, eye, and hotel models

Revision ID: 6bba0ccaf467
Revises: 9e1b86a85fe6
Create Date: 2025-11-07 03:36:18.419922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bba0ccaf467'
down_revision = '9e1b86a85fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dental_procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('eye_treatment_selections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('hotel_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_reservations', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('eye_treatment_selections', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('dental_procedures', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
