"""add logo_path to AppSettings

Revision ID: 735579d2a0e3
Revises: b2459c8bebc2
Create Date: 2025-11-07 12:06:16.712667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735579d2a0e3'
down_revision = 'b2459c8bebc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
