"""add_is_bot_message_to_messages

Revision ID: 787a6fe4b3f4
Revises: 65d93fe8079d
Create Date: 2025-11-10 22:37:43.940066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787a6fe4b3f4'
down_revision = '65d93fe8079d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bot_message', sa.Boolean(), nullable=True))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_bot_message')

    # ### end Alembic commands ###
