"""Add pricing configuration to distributor

Revision ID: 9e1b86a85fe6
Revises: 280cc95ef1af
Create Date: 2025-11-07 02:17:12.006955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1b86a85fe6'
down_revision = '280cc95ef1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_graft', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('price_per_graft')

    # ### end Alembic commands ###
