"""add AppSettings

Revision ID: b2459c8bebc2
Revises: 6bba0ccaf467
Create Date: 2025-11-07 04:06:34.139209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2459c8bebc2'
down_revision = '6bba0ccaf467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable_hair', sa.Boolean(), nullable=True),
    sa.Column('enable_teeth', sa.Boolean(), nullable=True),
    sa.Column('enable_eye', sa.Boolean(), nullable=True),
    sa.Column('enable_hotel', sa.Boolean(), nullable=True),
    sa.Column('enable_leads', sa.Boolean(), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.Column('navbar_style', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
