"""Add distributor integration fields

Revision ID: dcf1bc0a88ff
Revises: 8f90332f1cd5
Create Date: 2025-11-06 23:03:06.545249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf1bc0a88ff'
down_revision = '8f90332f1cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_page_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook_access_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('website_api_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('webhook_secret', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('webhook_secret')
        batch_op.drop_column('website_api_key')
        batch_op.drop_column('facebook_access_token')
        batch_op.drop_column('facebook_page_id')

    # ### end Alembic commands ###
