"""add aesthetic bariatric ivf checkup modules

Revision ID: f3f85488e7d7
Revises: 4450ff5aa6a9
Create Date: 2025-11-07 15:55:05.315552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f85488e7d7'
down_revision = '4450ff5aa6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aesthetic_procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('procedure_type', sa.String(length=50), nullable=False),
    sa.Column('procedure_name', sa.String(length=100), nullable=True),
    sa.Column('body_area', sa.String(length=50), nullable=True),
    sa.Column('measurements', sa.Text(), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('implant_size', sa.String(length=50), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('before_photo_path', sa.String(length=255), nullable=True),
    sa.Column('after_photo_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risks_explained', sa.Boolean(), nullable=True),
    sa.Column('consent_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bariatric_surgeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('surgery_type', sa.String(length=50), nullable=False),
    sa.Column('surgery_name', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('hypertension', sa.Boolean(), nullable=True),
    sa.Column('sleep_apnea', sa.Boolean(), nullable=True),
    sa.Column('previous_surgeries', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('expected_weight_loss', sa.String(length=50), nullable=True),
    sa.Column('hospital_stay_days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('package_includes', sa.Text(), nullable=True),
    sa.Column('diet_plan_provided', sa.Boolean(), nullable=True),
    sa.Column('follow_up_schedule', sa.Text(), nullable=True),
    sa.Column('risks_explained', sa.Boolean(), nullable=True),
    sa.Column('consent_signed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkup_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.Column('tests_included', sa.Text(), nullable=True),
    sa.Column('blood_test', sa.Boolean(), nullable=True),
    sa.Column('urine_test', sa.Boolean(), nullable=True),
    sa.Column('chest_xray', sa.Boolean(), nullable=True),
    sa.Column('ecg', sa.Boolean(), nullable=True),
    sa.Column('ultrasound', sa.Boolean(), nullable=True),
    sa.Column('mri', sa.Boolean(), nullable=True),
    sa.Column('ct_scan', sa.Boolean(), nullable=True),
    sa.Column('endoscopy', sa.Boolean(), nullable=True),
    sa.Column('colonoscopy', sa.Boolean(), nullable=True),
    sa.Column('mammography', sa.Boolean(), nullable=True),
    sa.Column('pap_smear', sa.Boolean(), nullable=True),
    sa.Column('bone_density', sa.Boolean(), nullable=True),
    sa.Column('cardiology_consult', sa.Boolean(), nullable=True),
    sa.Column('internal_medicine', sa.Boolean(), nullable=True),
    sa.Column('gynecology', sa.Boolean(), nullable=True),
    sa.Column('urology', sa.Boolean(), nullable=True),
    sa.Column('ophthalmology', sa.Boolean(), nullable=True),
    sa.Column('ent', sa.Boolean(), nullable=True),
    sa.Column('dermatology', sa.Boolean(), nullable=True),
    sa.Column('checkup_date', sa.Date(), nullable=True),
    sa.Column('results_ready', sa.Boolean(), nullable=True),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('abnormal_findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('report_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ivf_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type', sa.String(length=50), nullable=False),
    sa.Column('treatment_name', sa.String(length=100), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('female_age', sa.Integer(), nullable=True),
    sa.Column('male_partner', sa.String(length=100), nullable=True),
    sa.Column('infertility_duration_years', sa.Integer(), nullable=True),
    sa.Column('previous_pregnancies', sa.Integer(), nullable=True),
    sa.Column('previous_miscarriages', sa.Integer(), nullable=True),
    sa.Column('infertility_cause', sa.String(length=200), nullable=True),
    sa.Column('fsh_level', sa.Float(), nullable=True),
    sa.Column('lh_level', sa.Float(), nullable=True),
    sa.Column('amh_level', sa.Float(), nullable=True),
    sa.Column('estradiol_level', sa.Float(), nullable=True),
    sa.Column('sperm_count', sa.String(length=50), nullable=True),
    sa.Column('sperm_motility', sa.String(length=50), nullable=True),
    sa.Column('sperm_morphology', sa.String(length=50), nullable=True),
    sa.Column('stimulation_protocol', sa.String(length=100), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('egg_retrieval_date', sa.Date(), nullable=True),
    sa.Column('eggs_retrieved', sa.Integer(), nullable=True),
    sa.Column('eggs_fertilized', sa.Integer(), nullable=True),
    sa.Column('embryos_created', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('embryos_transferred', sa.Integer(), nullable=True),
    sa.Column('embryo_quality', sa.String(length=100), nullable=True),
    sa.Column('embryos_frozen', sa.Integer(), nullable=True),
    sa.Column('pregnancy_test_date', sa.Date(), nullable=True),
    sa.Column('pregnancy_result', sa.String(length=20), nullable=True),
    sa.Column('hcg_level', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('package_includes', sa.Text(), nullable=True),
    sa.Column('clinic_success_rate', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkup_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkup_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('test_category', sa.String(length=50), nullable=True),
    sa.Column('result_value', sa.String(length=100), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('result_file_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkup_id'], ['checkup_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkup_tests')
    op.drop_table('ivf_treatments')
    op.drop_table('checkup_packages')
    op.drop_table('bariatric_surgeries')
    op.drop_table('aesthetic_procedures')
    # ### end Alembic commands ###
